a1=int(input('Digite o valor do primeiro produto: '))
a2=int(input('Digite o valor do segundo produto: '))
a3=int(input('Digite o valor do terceiro produto: '))
a4=int(input('Digite o valor do quarto produto: '))
a5=int(input('Digite o valor do quinto produto: '))
soma=(a1+a2+a3+a4+a5)
print('O total a ser pago é {}'.format(soma))
pm=int(input('Digite o valor referente ao pagamento dos produtos: '))
troco=(pm-soma)
print('Sendo assim, o valor a ser recebido como troco é de {}'.format(troco))
