base=int(input('Digite o valor da base do retângulo: '))
altura=int(input('Digite o valor da altura do retângulo: '))
área=(base*altura)
áreatg=(base*altura)
if(área>100):área=('{} .Sendo assim, é um Terreno grande por se tratar de uma área de mais de 100'.format(áreatg))
print('A área do retângulo é {}'.format(área))