lado1=float(input('Digite o valor do primeiro lado do triângulo: '))
lado2=float(input('Digite o valor do segundo lado do triângulo: '))
lado3=float(input('Digite o valor do terceiro lado do triângulo: '))
if(lado1+lado2>lado3 and lado2+lado3>lado1 and lado1+lado3>lado2):print('Não é possível formar um triângulo com esses valores')
elif(lado1==lado2==lado3):print('Esse triângulo se trata de um triângulo equilátero')
elif(lado1==lado2!=lado3 and lado1!=lado2==lado3 and lado1==lado3!=lado2):print('Esse triângulo se trata de um triângulo isósceles')
elif(lado1!=lado2!=lado3):print('Esse triângulo se trata de um triângulo escaleno')